mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('personas/', include('personas.urls')), 
]

personas/urls.py
#import path
from django.urls import path

from . import views

app_name = 'personas'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:persona_id>/results/', views.results, name='results'),
    path('id/<int:persona_id>/', views.results),
    path('dni/<str:dni>/', views.get_for_dni, name='get_for_dni'),
    path('resultados/', views.resultados, name='resultados'),
]

personas/models.py
from django.db import models

# Create your models here.
class Persona(models.Model):
    apellido_materno = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    dni = models.CharField(max_length=20, unique=True)
    fecha_nacimiento = models.DateField()
    ubigeo = models.CharField(max_length=20)
    direccion = models.CharField(max_length=200)
    def __str__(self):
        return self.nombre + " " + self.apellido_paterno + " " + self.apellido_materno

personas/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.http import Http404
from .models import Persona
# Create your views here.
def index(request):
    personas_reniec = Persona.objects.all()
    #output = ", ".join([q.nombre for q in personas_reniec])
    #return HttpResponse(output) 
    #return HttpResponse("Hello, this is the Personas app index page.")
    #template = template.get_template('personas/index.html')
    context = {
        'personas_reniec': personas_reniec,
    }
    return render(request, 'personas/index.html', context)

def results(request, persona_id):
    try:
        persona = Persona.objects.get(pk=persona_id)
    except Persona.DoesNotExist:
        raise  Http404("Persona no encontrada")
    return HttpResponse(f"Resultados de la persona: {persona.nombre} {persona.apellido_paterno} {persona.apellido_materno}, DNI: {persona.dni}")

def get_for_dni(request, dni):
    try:
        persona = Persona.objects.get(dni=dni)
    except Persona.DoesNotExist:
        raise  Http404("Persona no encontrada")
    return render(request, 'personas/dni.html', {'persona': persona})

def resultados(request):
    apellido_paterno = request.POST['apellido_paterno']
    personas = Persona.objects.filter(apellido_paterno=apellido_paterno)
    #return HttpResponse(f"Resultados de la búsqueda para apellido paterno: {apellido_paterno}")
    if personas is None:
        raise Http404("No se encontraron personas con los datos proporcionados.")
    return render(request, 'personas/resultados.html', {'personas': personas})

personas/templates/personas/dni.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Detalle de Persona</title>
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="container mt-5">
      <h1 class="mb-4">Detalle de Persona</h1>
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">{{ persona.nombre }}</h2>
          <p>{{persona.apellido_paterno}} {{persona.apellido_materno}}</p>
          <p class="card-text"><strong>DNI:</strong> {{ persona.dni }}</p>
          <p class="card-text">
            <strong>Fecha de Nacimiento:</strong> {{ persona.fecha_nacimiento }}
          </p>
          <p class="card-text">
            <strong>Dirección:</strong> {{ persona.direccion }}
          </p>
          <p>
            <strong>ubigeo</strong> {{}}
          </p>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

personas/templates/personas/index.html
{% comment %} {% if personas_reniec %}
<h1>Listado de Personas RENIEC</h1>
{% for persona in personas_reniec %}
<div>
  <h2>{{ persona.nombre }}</h2>
  <p>DNI: {{ persona.dni }}</p>
  <p>Fecha de Nacimiento: {{ persona.fecha_nacimiento }}</p>
  <p>Dirección: {{ persona.direccion }}</p>
</div>
{% endfor %} {% else %}
<p>Sin registros de personas en la base de datos</p>
{% endif %} {% endcomment %}

<form action="{% url 'personas:resultados' %}" method="POST">
  {% csrf_token %}
  <fieldset>
    <legend><h1>Buscador de personas</h1></legend>
    <label for="nombres">Nombres de persona</label><br />
    <input
      type="text"
      name="nombres"
      id="nombres"
      placeholder="Edwin Antonio"
    />
    <br/>
    <label for="apellidos_paterno">Apellido paterno</label><br />
    <input
      type="text"
      name="apellido_paterno"
      id="apellido_paterno"
      placeholder="Hinojosa"
    /><br/>
    <label for="apellido_materno">Apellido materno</label><br />
    <input
      type="text"
      name="apellido_materno"
      id="apellido_materno"
      placeholder="Ramos"
    />
  </fieldset>
  <input type="submit" value="Buscar" />
</form>

personas/templates/personas/resultados.html
{% for persona in personas %}
{{persona.nombre}} {{persona.apellido_paterno}} {{persona.apellido_materno}} - {{persona.dni}} <br/>
{% endfor %}